# Generated by Django 3.2.7 on 2021-10-04 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitasjp', '0002_receita_pessoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
    ]
